// =============================================================================
// studies/06_yields_tables/print_yields_latex.C
// PURPOSE: Reads pre-fit histograms and prints LaTeX yield tables for Overleaf.
//          One table per region with per-process yields ± stat uncertainty.
//          Also prints a combined summary table across all regions.
//          Post-fit table applies mu_tt=0.67, mu_ztautau=1.26.
// INPUTS:  plots/04_prefit/prefit_histograms.root
// OUTPUTS: stdout + outputs/tables/yields_prefit.tex + outputs/tables/yields_postfit.tex
// =============================================================================
#include "../plotting/PlottingUtils.h"
#include <fstream>
#include <iomanip>
#include <cmath>

struct YieldRow {
    std::string name;
    std::string title;
    double val;
    double err;
};

void printLatexTable(const std::vector<YieldRow>& rows,
                     const char* caption,
                     const char* label,
                     std::ofstream& out)
{
    out << "\\begin{table}[htbp]\n";
    out << "\\centering\n";
    out << "\\caption{" << caption << "}\n";
    out << "\\label{" << label << "}\n";
    out << "\\begin{tabular}{lc}\n";
    out << "\\toprule\n";
    out << "Process & Yield $\\pm$ stat. unc. \\\\\n";
    out << "\\midrule\n";

    double totalMC=0., totalMCerr2=0.;
    for (const auto& row : rows) {
        if (row.name == "separator") { out << "\\midrule\n"; continue; }
        out << row.title << " & $"
            << std::fixed << std::setprecision(1) << row.val
            << " \\pm " << row.err << "$ \\\\\n";
        if (row.name != "Data" && row.name != "Total") {
            totalMC += row.val; totalMCerr2 += row.err*row.err;
        }
    }

    out << "\\bottomrule\n";
    out << "\\end{tabular}\n";
    out << "\\end{table}\n\n";
}

void print_yields_latex()
{
    makeDir("outputs/tables");

    TFile* fin = TFile::Open("../plotting/outputs/06_prefit/prefit_histograms.root");
    if (!fin || fin->IsZombie()) {
        printf("ERROR: prefit_histograms.root not found — run plot_prefit.C first\n");
        return;
    }

    std::vector<std::string> regNames  = {"SR","VR","CR_tt","CR_ztautau"};
    std::vector<std::string> regLabels = {
        "Signal Region","Validation Region",
        "CR ($t\\bar{t}$)","CR ($Z\\rightarrow\\tau\\tau$)"
    };
    std::vector<std::string> procNames = {"ttbar","ztautau","diboson","singletop","wjets","higgs","fake"};
    std::map<std::string, std::string> procTex = {
        {"ttbar",     "$t\\bar{t}$"},
        {"ztautau",   "$Z\\rightarrow\\tau\\tau$"},
        {"diboson",   "Diboson"},
        {"singletop", "Single top"},
        {"wjets",     "$W$+jets"},
        {"higgs",     "Higgs"},
        {"fake",      "Fake/Non-Prompt"},
        {"Total",     "\\textbf{Total prediction}"},
        {"Data",      "\\textbf{Data}"},
    };

    const double mu_tt = 0.67, mu_ztau = 1.26;

    std::ofstream preFile("outputs/tables/yields_prefit.tex");
    std::ofstream postFile("outputs/tables/yields_postfit.tex");

    // Header
    preFile  << "% Pre-fit yields — generated by print_yields_latex.C\n";
    postFile << "% Post-fit yields (mu_tt=" << mu_tt << ", mu_ztautau=" << mu_ztau
             << ") — generated by print_yields_latex.C\n\n";
    preFile  << "\\usepackage{booktabs}\n\n";
    postFile << "\\usepackage{booktabs}\n\n";

    // -------------------------------------------------------------------------
    // Combined multi-region table (all regions in columns)
    // -------------------------------------------------------------------------
    auto makeMultiColTable = [&](bool postfit, std::ofstream& out) {
        out << "\\begin{table}[htbp]\n\\centering\n";
        out << "\\caption{" << (postfit?"Post":"Pre") << "-fit event yields in all analysis regions.";
        if (postfit) out << " Normalization factors: $\\mu_{t\\bar{t}}=" << mu_tt
                         << "$, $\\mu_{Z\\tau\\tau}=" << mu_ztau << "$.";
        out << "}\n";
        out << "\\label{tab:yields_" << (postfit?"post":"pre") << "fit}\n";
        out << "\\resizebox{\\textwidth}{!}{\n";
        out << "\\begin{tabular}{l";
        for (int i=0;i<(int)regNames.size();++i) out << "c";
        out << "}\n\\toprule\n";
        out << "Process";
        for (const auto& rl : regLabels) out << " & " << rl;
        out << " \\\\\n\\midrule\n";

        for (const auto& p : procNames) {
            out << procTex.count(p) ? procTex.at(p) : p;
            for (const auto& rn : regNames) {
                TH1D* h = (TH1D*)fin->Get(TString::Format("%s_%s",p.c_str(),rn.c_str()));
                double val=0., err=0.;
                if (h) {
                    val = h->Integral();
                    for (int b=1;b<=h->GetNbinsX();++b) {
                        double e=h->GetBinError(b); err+=e*e;
                    }
                    err = std::sqrt(err);
                    if (postfit) {
                        if (p=="ttbar")   { val*=mu_tt;   err*=mu_tt; }
                        if (p=="ztautau") { val*=mu_ztau; err*=mu_ztau; }
                    }
                }
                out << std::fixed << std::setprecision(1)
                    << " & $" << val << " \\pm " << err << "$";
            }
            out << " \\\\\n";
        }
        out << "\\midrule\n";
        // Total prediction
        out << "\\textbf{Total prediction}";
        for (const auto& rn : regNames) {
            TH1D* hT = (TH1D*)fin->Get(TString::Format("total_%s",rn.c_str()));
            double val=0.,err=0.;
            if (hT) {
                // Rebuild from individual histograms if postfit
                if (postfit) {
                    for (const auto& p:procNames) {
                        TH1D* h=(TH1D*)fin->Get(TString::Format("%s_%s",p.c_str(),rn.c_str()));
                        if(!h) continue;
                        double sc=(p=="ttbar")?mu_tt:(p=="ztautau")?mu_ztau:1.;
                        val += h->Integral()*sc;
                        for(int b=1;b<=h->GetNbinsX();++b){double e=h->GetBinError(b)*sc;err+=e*e;}
                    }
                    err=std::sqrt(err);
                } else {
                    if(hT){val=hT->Integral();for(int b=1;b<=hT->GetNbinsX();++b){double e=hT->GetBinError(b);err+=e*e;}err=std::sqrt(err);}
                }
            }
            out << std::fixed << std::setprecision(1)
                << " & $\\mathbf{" << val << " \\pm " << err << "}$";
        }
        out << " \\\\\n\\midrule\n";
        // Data
        out << "\\textbf{Data}";
        for (const auto& rn : regNames) {
            bool isSR=(rn=="SR");
            if (isSR) { out << " & --"; continue; }
            TH1D* h=(TH1D*)fin->Get(TString::Format("data_%s",rn.c_str()));
            double val=h?h->Integral():0.;
            out << " & " << std::fixed << std::setprecision(0) << val;
        }
        out << " \\\\\n\\bottomrule\n\\end{tabular}\n}\n\\end{table}\n\n";
    };

    makeMultiColTable(false, preFile);
    makeMultiColTable(true,  postFile);

    fin->Close();
    preFile.close(); postFile.close();

    printf("\n=== print_yields_latex done ===\n");
    printf("  Pre-fit table:  outputs/tables/yields_prefit.tex\n");
    printf("  Post-fit table: outputs/tables/yields_postfit.tex\n");
    printf("  Copy \\input{outputs/tables/yields_prefit.tex} into your Overleaf document.\n");
}
